### ISSUE TITLE
Cron Groups not working

### ISSUE THREAD

**Issue by fcorriga** [AOEpeople/Aoe_Scheduler#130] opened 2015-07-03 16:50 UTC
Here's my test cron (in /etc/cron.d/test)

```* * * * *        magento           sleep 10; /bin/bash /var/www/test/scheduler_cron.sh --mode always --excludeGroups GroupMail```
```* * * * *        magento           sleep 10; /bin/bash /var/www/test/scheduler_cron.sh --mode default --excludeGroups GroupMail```

All files are owned by user "magento". 
I defined 1 single group called GroupMail for 3 jobs in the scheduler and all jobs (including those belonging to GroupMail) are still being scheduled and executed as if there was no exclusion (cron was reloaded and all caches are disabled)

What i'm doing wrong? Or is there a bug?

P.S.: Magento CE 1.9.1 running on HHVM 3.6.4 & Aoe_Scheduler just cloned from master.

P.P.S.: Ok, i've found i overlooked the always/default modes. The always jobs are always executed, so i reconfigured my cron and it now works as expected.

**Comment by ajpevers** [comment] 2015-07-10 07:57
It's a bug. shell/scheduler.php does not yet take the (in/ex)cludeGroups and (in/ex)cludeJobs into account. And the 'always' cron lacks even more.

**Comment by fcorriga** [comment] 2015-07-10 08:58
i use "always" for the jobs i need to run always and default for the other jobs and it all seems to work as expected. i don't know if default is excluding GroupMail... however it actually works for my needs.

**Comment by ajpevers** [comment] 2015-07-10 09:08
Good for you :+1: Still the groups are a broken functionality so your issue is still worth fixing.

**Comment by ajpevers** [comment] 2015-07-10 09:11
I've made a pull request for the default cron job that fixes cron groups there. The always cron action sets include and exclude groups and jobs on a jobs collection but those are never retrieved anywhere in the code, so they never make it through as a collection filter. This is too much work for me now but I'll see if I get to a pull request sometime.

**Comment by fcorriga** [comment] 2015-07-10 14:08
thanks for your effort

**Comment by LeeSaferite** [comment] 2015-07-13 14:38
The always job was never written to support groups to my knowledge, but I'm willing to merge a PR asking that functionality.

**Comment by fcorriga** [comment] 2015-07-13 14:45
Mine was a test case, however, personally i do not need that functionality (groups inclusion/exclusion) in the "always" jobs.

**Comment by ajpevers** [comment] 2015-07-14 10:27
In that case: https://github.com/AOEpeople/Aoe_Scheduler/pull/137

**Comment by fcorriga** [comment] 2015-07-14 16:16
seems legit.
you can already exclude groups or jobs by replacing the "always" expression with something else from the aoe_scheduler backend config. No need to explicitly add --exclude* option for the always cron.

**Comment by fbrnc** [comment] 2015-08-15 05:11
@LeeSaferite, is this issue now solved by #148? Or is there another issue related to cron groups that's not caused by the wrong locks?

**Comment by LeeSaferite** [comment] 2015-08-17 14:09
This was resolved in #135 for both the `default` and `always` cron dispatchers.

**Closed by LeeSaferite** 2015-08-17 14:09 UTC
